version: '3.4'

services:
  fivem:
    image: petchstudio/fivem
    environment:
      TZ: Asia/Bangkok
    stdin_open: true
    tty: true
    volumes:
      # You must provide a server config file
      - ./server.cfg:/srv/server.cfg
      - ./cfx-server-data/resources:/srv/resources
      - ./cfx-server-data/cache:/srv/cache
    ports:
      - "30120:30120/tcp"
      - "30120:30120/udp"
